# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpc_pb2 as proto_dot_grpc__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindUser = channel.unary_unary(
                '/API/FindUser',
                request_serializer=proto_dot_grpc__pb2.FindRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.User.FromString,
                )
        self.StreamUsers = channel.unary_stream(
                '/API/StreamUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.User.FromString,
                )
        self.ListUsers = channel.unary_unary(
                '/API/ListUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.ListUserResponse.FromString,
                )
        self.FindMusic = channel.unary_unary(
                '/API/FindMusic',
                request_serializer=proto_dot_grpc__pb2.FindRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.Music.FromString,
                )
        self.StreamMusics = channel.unary_stream(
                '/API/StreamMusics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.Music.FromString,
                )
        self.ListMusics = channel.unary_unary(
                '/API/ListMusics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.ListMusicResponse.FromString,
                )
        self.FindPlaylist = channel.unary_unary(
                '/API/FindPlaylist',
                request_serializer=proto_dot_grpc__pb2.FindRequest.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.Playlist.FromString,
                )
        self.StreamPlaylists = channel.unary_stream(
                '/API/StreamPlaylists',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.Playlist.FromString,
                )
        self.ListPlaylists = channel.unary_unary(
                '/API/ListPlaylists',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_grpc__pb2.ListPlaylistResponse.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMusics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMusics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUser,
                    request_deserializer=proto_dot_grpc__pb2.FindRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.User.SerializeToString,
            ),
            'StreamUsers': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_grpc__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_grpc__pb2.ListUserResponse.SerializeToString,
            ),
            'FindMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.FindMusic,
                    request_deserializer=proto_dot_grpc__pb2.FindRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.Music.SerializeToString,
            ),
            'StreamMusics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMusics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_grpc__pb2.Music.SerializeToString,
            ),
            'ListMusics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMusics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_grpc__pb2.ListMusicResponse.SerializeToString,
            ),
            'FindPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPlaylist,
                    request_deserializer=proto_dot_grpc__pb2.FindRequest.FromString,
                    response_serializer=proto_dot_grpc__pb2.Playlist.SerializeToString,
            ),
            'StreamPlaylists': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlaylists,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_grpc__pb2.Playlist.SerializeToString,
            ),
            'ListPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylists,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_grpc__pb2.ListPlaylistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/FindUser',
            proto_dot_grpc__pb2.FindRequest.SerializeToString,
            proto_dot_grpc__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/API/StreamUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_grpc__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/ListUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_grpc__pb2.ListUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/FindMusic',
            proto_dot_grpc__pb2.FindRequest.SerializeToString,
            proto_dot_grpc__pb2.Music.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamMusics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/API/StreamMusics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_grpc__pb2.Music.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListMusics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/ListMusics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_grpc__pb2.ListMusicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/FindPlaylist',
            proto_dot_grpc__pb2.FindRequest.SerializeToString,
            proto_dot_grpc__pb2.Playlist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/API/StreamPlaylists',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_grpc__pb2.Playlist.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/ListPlaylists',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_grpc__pb2.ListPlaylistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
