# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/grpc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/grpc.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x04\"E\n\x05Music\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x12\n\nplaylistId\x18\x04 \x01(\t\"4\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\"\x19\n\x0b\x46indRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x10ListUserResponse\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"+\n\x11ListMusicResponse\x12\x16\n\x06musics\x18\x01 \x03(\x0b\x32\x06.Music\"4\n\x14ListPlaylistResponse\x12\x1c\n\tplaylists\x18\x01 \x03(\x0b\x32\t.Playlist2\xbe\x03\n\x03\x41PI\x12\x1f\n\x08\x46indUser\x12\x0c.FindRequest\x1a\x05.User\x12.\n\x0bStreamUsers\x12\x16.google.protobuf.Empty\x1a\x05.User0\x01\x12\x36\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x11.ListUserResponse\x12!\n\tFindMusic\x12\x0c.FindRequest\x1a\x06.Music\x12\x30\n\x0cStreamMusics\x12\x16.google.protobuf.Empty\x1a\x06.Music0\x01\x12\x38\n\nListMusics\x12\x16.google.protobuf.Empty\x1a\x12.ListMusicResponse\x12\'\n\x0c\x46indPlaylist\x12\x0c.FindRequest\x1a\t.Playlist\x12\x36\n\x0fStreamPlaylists\x12\x16.google.protobuf.Empty\x1a\t.Playlist0\x01\x12>\n\rListPlaylists\x12\x16.google.protobuf.Empty\x1a\x15.ListPlaylistResponseB\x1fZ\x1dgithub.com/iaggo/go/proto/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035github.com/iaggo/go/proto/api'
  _globals['_USER']._serialized_start=49
  _globals['_USER']._serialized_end=94
  _globals['_MUSIC']._serialized_start=96
  _globals['_MUSIC']._serialized_end=165
  _globals['_PLAYLIST']._serialized_start=167
  _globals['_PLAYLIST']._serialized_end=219
  _globals['_FINDREQUEST']._serialized_start=221
  _globals['_FINDREQUEST']._serialized_end=246
  _globals['_LISTUSERRESPONSE']._serialized_start=248
  _globals['_LISTUSERRESPONSE']._serialized_end=288
  _globals['_LISTMUSICRESPONSE']._serialized_start=290
  _globals['_LISTMUSICRESPONSE']._serialized_end=333
  _globals['_LISTPLAYLISTRESPONSE']._serialized_start=335
  _globals['_LISTPLAYLISTRESPONSE']._serialized_end=387
  _globals['_API']._serialized_start=390
  _globals['_API']._serialized_end=836
# @@protoc_insertion_point(module_scope)
